import type { CaptureShot } from './types'

type CaptureOverride = Pick<
  CaptureShot,
  'type' | 'target' | 'actions' | 'targetText' | 'padding' | 'minWidth' | 'minHeight'
>

const overrides: Record<string, CaptureOverride> = {
  'news__leer-avisos__paso-01-tarjetas-y-detalle': {
    type: 'seccion',
    target: { css: '[data-manual-capture="news-card"]' },
    padding: 16,
    minWidth: 480,
    minHeight: 180,
  },
  'viaticos__crear-y-seguir__paso-01-crear-viatico-o-reintegro': {
    type: 'modal',
    actions: [
      { type: 'click', target: { role: 'button', name: 'Crear viático o reintegro', exact: true } },
      { type: 'wait', target: { role: 'dialog' }, state: 'visible', timeout: 15_000 },
    ],
    target: { role: 'dialog' },
    targetText: ['Crear viático o reintegro', 'Asunto', 'Área Solicitante'],
    padding: 12,
    minWidth: 480,
    minHeight: 360,
  },
  'viaticos__crear-y-seguir__paso-02-ojo-lapiz-y-filtros': {
    type: 'seccion',
    actions: [
      { type: 'click', target: { role: 'button', name: 'Filtros', exact: true } },
      { type: 'wait', target: '.filters-panel', state: 'visible', timeout: 10_000 },
    ],
    target: { manualCapture: 'data-table' },
    targetText: ['Mis viáticos y reintegros', 'Filtros', 'Estado'],
    padding: 12,
    minWidth: 640,
    minHeight: 280,
  },
  'basedatos-clientes__buscar-y-filtrar__paso-01-encontrar-a-alguien': {
    type: 'seccion',
    actions: [
      { type: 'click', target: { role: 'button', name: 'Filtros', exact: true } },
      { type: 'wait', target: '.filters-panel', state: 'visible', timeout: 10_000 },
    ],
    target: { manualCapture: 'data-table' },
    targetText: ['Base de datos de clientes', 'Filtros', 'Servicio'],
    padding: 12,
    minWidth: 640,
    minHeight: 280,
  },
  'basedatos-clientes__ver-la-ficha-del-cliente__paso-01-abrir-detalles': {
    type: 'destino',
    actions: [
      { type: 'click', target: { css: '[data-manual-capture="data-table-grid"] tbody tr:first-child button' } },
      { type: 'wait', target: { text: 'Detalles del Cliente' }, state: 'visible', timeout: 15_000 },
    ],
    target: { role: 'main' },
    targetText: ['Detalles del Cliente'],
    padding: 16,
    minWidth: 640,
    minHeight: 360,
  },
  'basedatos-clientes__ver-la-ficha-del-cliente__paso-02-portal-y-contrasena': {
    type: 'seccion',
    actions: [
      { type: 'click', target: { css: '[data-manual-capture="data-table-grid"] tbody tr:first-child button' } },
      { type: 'wait', target: { text: 'Detalles del Cliente' }, state: 'visible', timeout: 15_000 },
    ],
    target: { text: 'recuperación de contraseña' },
    targetText: ['recuperación de contraseña'],
    padding: 16,
    minWidth: 420,
    minHeight: 180,
  },
  'basedatos-permisos__consultar__paso-01-listado-y-filtros': {
    type: 'seccion',
    actions: [
      { type: 'click', target: { role: 'button', name: 'Filtros', exact: true } },
      { type: 'wait', target: '.filters-panel', state: 'visible', timeout: 10_000 },
    ],
    target: { manualCapture: 'data-table' },
    targetText: ['Permisos', 'Filtros', 'Estado'],
    padding: 12,
    minWidth: 640,
    minHeight: 280,
  },
  'basedatos-permisos__documentos-seguimiento-y-pagos__paso-01-tres-secciones': {
    type: 'destino',
    actions: [
      { type: 'click', target: { css: 'button[title="Ver documentos"]' } },
      { type: 'wait', target: { text: 'Documentos por trámite' }, state: 'visible', timeout: 15_000 },
    ],
    target: { text: 'Documentos por trámite' },
    targetText: ['Documentos por trámite', 'Seguimiento', 'Pagos'],
    padding: 16,
    minWidth: 640,
    minHeight: 360,
  },
  'basedatos-permisos__estado-editar-o-quitar__paso-01-estado-en-la-tabla': {
    type: 'seccion',
    actions: [
      { type: 'click', target: { css: '[data-manual-capture="data-table-grid"] tbody tr:first-child td button' } },
      { type: 'wait', target: { text: 'Rechazado' }, state: 'visible', timeout: 8_000 },
    ],
    target: { manualCapture: 'data-table' },
    targetText: ['Estado', 'Rechazado'],
    padding: 12,
    minWidth: 640,
    minHeight: 280,
  },
  'verificacion__confirmar-u-observar-un-voucher__paso-01-abrir-el-detalle': {
    type: 'destino',
    actions: [
      { type: 'click', target: { css: '[data-manual-capture="data-table-grid"] tbody tr:first-child button' } },
      { type: 'wait', ms: 2_000 },
    ],
    target: { role: 'main' },
    targetText: ['Pagado'],
    padding: 16,
    minWidth: 640,
    minHeight: 280,
  },
  'verificacion__consultar-la-bandeja__paso-01-elegir-pestana-y-filtrar': {
    type: 'seccion',
    actions: [
      { type: 'click', target: { role: 'button', name: 'Filtros', exact: true } },
      { type: 'wait', target: '.filters-panel', state: 'visible', timeout: 10_000 },
    ],
    target: { manualCapture: 'data-table' },
    targetText: ['Verificación', 'Filtros', 'Consolidado'],
    padding: 12,
    minWidth: 640,
    minHeight: 280,
  },
  'viaticos-completados__consultar-el-historico__paso-01-filtrar-y-exportar': {
    type: 'seccion',
    actions: [
      { type: 'click', target: { role: 'button', name: 'Filtros', exact: true } },
      { type: 'wait', target: '.filters-panel', state: 'visible', timeout: 10_000 },
    ],
    target: { manualCapture: 'data-table' },
    targetText: ['Filtros'],
    padding: 12,
    minWidth: 640,
    minHeight: 280,
  },
  'viaticos-pendientes__atender-un-pendiente__paso-01-entrar-al-detalle': {
    type: 'seccion',
    actions: [
      { type: 'click', target: { role: 'button', name: 'Filtros', exact: true } },
      { type: 'wait', target: '.filters-panel', state: 'visible', timeout: 10_000 },
    ],
    target: { manualCapture: 'data-table' },
    targetText: ['Filtros'],
    padding: 12,
    minWidth: 640,
    minHeight: 280,
  },
  'cargaconsolidada-completados__clientes__paso-01-ficha-y-firma': {
    type: 'destino',
    actions: [
      { type: 'click', target: { css: '[data-manual-capture="data-table-grid"] tbody tr:first-child button' } },
      { type: 'wait', target: { text: 'Pasos de Carga Consolidada' }, state: 'visible', timeout: 15_000 },
      { type: 'click', target: { text: 'Clientes' } },
      { type: 'wait', target: { text: 'Clientes' }, state: 'visible', timeout: 15_000 },
    ],
    target: { role: 'main' },
    targetText: ['Clientes'],
    padding: 16,
    minWidth: 640,
    minHeight: 280,
  },
  'cargaconsolidada-completados__cotizacion-final__paso-01-pestana-pagos': {
    type: 'destino',
    actions: [
      { type: 'click', target: { css: '[data-manual-capture="data-table-grid"] tbody tr:first-child button' } },
      { type: 'wait', target: { text: 'Pasos de Carga Consolidada' }, state: 'visible', timeout: 15_000 },
      { type: 'click', target: { text: 'Cotizacion final' } },
      { type: 'wait', target: { text: 'Pagos' }, state: 'visible', timeout: 15_000 },
    ],
    target: { role: 'main' },
    targetText: ['Pagos'],
    padding: 16,
    minWidth: 640,
    minHeight: 280,
  },
  'cargaconsolidada-completados__cotizacion__paso-01-pagos': {
    type: 'destino',
    actions: [
      { type: 'click', target: { css: '[data-manual-capture="data-table-grid"] tbody tr:first-child button' } },
      { type: 'wait', target: { text: 'Pasos de Carga Consolidada' }, state: 'visible', timeout: 15_000 },
      { type: 'click', target: { text: 'Cotizacion', exact: true } },
      { type: 'wait', target: { text: 'Pagos' }, state: 'visible', timeout: 15_000 },
    ],
    target: { role: 'main' },
    targetText: ['Pagos'],
    padding: 16,
    minWidth: 640,
    minHeight: 280,
  },
  'cargaconsolidada-completados__documentacion__paso-01-descargar-plantillas': {
    type: 'destino',
    actions: [
      { type: 'click', target: { css: '[data-manual-capture="data-table-grid"] tbody tr:first-child button' } },
      { type: 'wait', target: { text: 'Pasos de Carga Consolidada' }, state: 'visible', timeout: 15_000 },
      { type: 'click', target: { text: 'Documentacion' } },
      { type: 'wait', target: { text: 'Documentación' }, state: 'visible', timeout: 15_000 },
    ],
    target: { role: 'main' },
    targetText: ['Documentación'],
    padding: 16,
    minWidth: 640,
    minHeight: 280,
  },
  'cargaconsolidada-completados__entrega__paso-01-agenda-y-formulario': {
    type: 'destino',
    actions: [
      { type: 'click', target: { css: '[data-manual-capture="data-table-grid"] tbody tr:first-child button' } },
      { type: 'wait', target: { text: 'Pasos de Carga Consolidada' }, state: 'visible', timeout: 15_000 },
      { type: 'click', target: { text: 'Entrega' } },
      { type: 'wait', target: { text: 'Entrega' }, state: 'visible', timeout: 15_000 },
    ],
    target: { role: 'main' },
    targetText: ['Entrega'],
    padding: 16,
    minWidth: 640,
    minHeight: 280,
  },
  'cargaconsolidada-completados__factura-y-guia__paso-01-enviar-formulario': {
    type: 'destino',
    actions: [
      { type: 'click', target: { css: '[data-manual-capture="data-table-grid"] tbody tr:first-child button' } },
      { type: 'wait', target: { text: 'Pasos de Carga Consolidada' }, state: 'visible', timeout: 15_000 },
      { type: 'click', target: { text: 'Factura y guia' } },
      { type: 'wait', target: { text: 'Factura' }, state: 'visible', timeout: 15_000 },
    ],
    target: { role: 'main' },
    targetText: ['Factura'],
    padding: 16,
    minWidth: 640,
    minHeight: 280,
  },
  'curso-alumnos__consultar-y-filtrar-alumnos__paso-01-entrar-al-listado': {
    type: 'seccion',
    actions: [
      { type: 'click', target: { role: 'button', name: 'Filtros', exact: true } },
      { type: 'wait', target: '.filters-panel', state: 'visible', timeout: 10_000 },
    ],
    target: { manualCapture: 'data-table' },
    targetText: ['Filtros'],
    padding: 12,
    minWidth: 640,
    minHeight: 280,
  },
  'curso-campanas__consultar-campanas__paso-01-abrir-el-listado': {
    type: 'seccion',
    target: { manualCapture: 'data-table' },
    targetText: ['Campaña'],
    padding: 12,
    minWidth: 640,
    minHeight: 280,
  },
  'basedatos-boletin-quimico__consultar__paso-01-buscar-el-boletin': {
    type: 'seccion',
    target: { manualCapture: 'data-table' },
    targetText: ['Boletín Químico'],
    padding: 12,
    minWidth: 640,
    minHeight: 280,
  },
  'basedatos-boletin-quimico__crear-nuevo__paso-01-carga-cliente-e-items': {
    type: 'modal',
    actions: [
      { type: 'click', target: { role: 'button', name: 'Nuevo', exact: true } },
      { type: 'wait', target: { role: 'dialog' }, state: 'visible', timeout: 15_000 },
      { type: 'wait', ms: 2_500 },
    ],
    target: { role: 'dialog' },
    targetText: ['Nuevo Boletín Químico', 'Consolidado'],
    padding: 12,
    minWidth: 420,
    minHeight: 240,
  },
  'cotizaciones__crear-o-editar-con-el-asistente__paso-01-paso-1-informacion-del-cliente': {
    type: 'destino',
    actions: [
      { type: 'click', target: { role: 'button', name: 'Crear Cotización', exact: true } },
      { type: 'wait', target: { text: 'Información del Cliente' }, state: 'visible', timeout: 20_000 },
    ],
    target: { role: 'main' },
    targetText: ['Información del Cliente', 'tipo de cliente'],
    padding: 16,
    minWidth: 640,
    minHeight: 360,
  },
  'soporte-ti__crear-una-solicitud__paso-01-nueva-solicitud': {
    type: 'modal',
    actions: [
      { type: 'click', target: { role: 'button', name: 'Nueva solicitud', exact: true } },
      { type: 'wait', target: { role: 'dialog' }, state: 'visible', timeout: 15_000 },
    ],
    target: { role: 'dialog' },
    targetText: ['Nueva solicitud'],
    padding: 12,
    minWidth: 420,
    minHeight: 360,
  },
  'cotizaciones__trabajar-desde-el-listado__paso-01-buscar-filtrar-y-exportar': {
    type: 'seccion',
    actions: [
      { type: 'click', target: { role: 'button', name: 'Filtros', exact: true } },
      { type: 'wait', target: '.filters-panel', state: 'visible', timeout: 10_000 },
    ],
    target: { manualCapture: 'data-table' },
    targetText: ['Cotizaciones', 'Filtros', 'Exportar'],
    padding: 12,
    minWidth: 640,
    minHeight: 280,
  },
}

export function captureOverride(captureKey: string): CaptureOverride | undefined {
  return overrides[captureKey]
}
