import { WS_EVENTS } from '~/config/websocket/events-config'
import { WA_INBOX_WS_EVENTS } from '~/constants/whatsappInboxWs'
import { SOPORTE_TI_WS_EVENTS } from '~/constants/soporteTi'
import { SEGUIMIENTO_DRIVE_WS_EVENT } from '~/composables/cargaconsolidada/seguimiento-drive/constants'
import { WS_NOTIFICATION_KEYS } from './keys'

/**
 * Mapeo evento websocket → clave del catálogo de preferencias.
 * Varios eventos pueden compartir la misma clave (p. ej. calendario created/updated/deleted).
 */
export const WS_EVENT_TO_NOTIFICATION_KEY: Record<string, string> = {
  [WS_EVENTS.COTIZACION_STATUS_UPDATED]: WS_NOTIFICATION_KEYS.COTIZACION_ESTADO,
  [WS_EVENTS.COTIZACION_NEW_REQUEST]: WS_NOTIFICATION_KEYS.COTIZACION_NUEVA,
  [WS_EVENTS.COTIZACION_CHINA_CONTACTED]: WS_NOTIFICATION_KEYS.COTIZACION_CHINA_CONTACTADO,
  [WS_EVENTS.COTIZACION_CHANGE_CONTAINER]: WS_NOTIFICATION_KEYS.COTIZACION_CARGA_ROLEADA,
  [WS_EVENTS.COTIZACION_CHINA_RECEIVED]: WS_NOTIFICATION_KEYS.COTIZACION_CHINA_RECIBIDA,
  [WS_EVENTS.COTIZACION_CHINA_INSPECTIONED]: WS_NOTIFICATION_KEYS.COTIZACION_CHINA_INSPECCIONADA,

  [WS_EVENTS.CONTAINER_STATUS_CHANGE]: WS_NOTIFICATION_KEYS.CONTENEDOR_ESTADO,
  [WS_EVENTS.CONTAINER_NEW]: WS_NOTIFICATION_KEYS.CONTENEDOR_NUEVO,
  [WS_EVENTS.CONTAINER_ACTIVITY]: WS_NOTIFICATION_KEYS.CONTENEDOR_ACTIVIDAD,

  [WS_EVENTS.DOCUMENT_NEW]: WS_NOTIFICATION_KEYS.DOCUMENTO_NUEVO,
  [WS_EVENTS.DOCUMENT_STATUS_CHANGE]: WS_NOTIFICATION_KEYS.DOCUMENTO_ESTADO,
  [WS_EVENTS.DOCUMENT_REQUEST]: WS_NOTIFICATION_KEYS.DOCUMENTO_SOLICITUD,
  [WS_EVENTS.IMPORTACION_EXCEL_COMPLETED]: WS_NOTIFICATION_KEYS.IMPORTACION_EXCEL,
  [WS_EVENTS.PLANTILLA_FINAL_BATCH_FINISHED]: WS_NOTIFICATION_KEYS.PLANTILLA_FINAL_LOTE,

  [WS_EVENTS.USUARIO_DATOS_FACTURACION_IMPORT_FINISHED]: WS_NOTIFICATION_KEYS.FACTURACION_IMPORTACION,

  [WS_EVENTS.STOCK_UPDATE]: WS_NOTIFICATION_KEYS.ALMACEN_STOCK,
  [WS_EVENTS.WAREHOUSE_ALERT]: WS_NOTIFICATION_KEYS.ALMACEN_ALERTA,

  [WS_EVENTS.TASK_ASSIGNMENT]: WS_NOTIFICATION_KEYS.COORDINACION_TAREA,
  [WS_EVENTS.SCHEDULE_UPDATE]: WS_NOTIFICATION_KEYS.COORDINACION_HORARIO,

  [WS_EVENTS.REINTEGRO_REQUEST]: WS_NOTIFICATION_KEYS.VIATICO_REINTEGRO,

  [WS_EVENTS.CALENDAR_ACTIVITY_CREATED]: WS_NOTIFICATION_KEYS.CALENDARIO_ACTIVIDAD,
  [WS_EVENTS.CALENDAR_ACTIVITY_UPDATED]: WS_NOTIFICATION_KEYS.CALENDARIO_ACTIVIDAD,
  [WS_EVENTS.CALENDAR_ACTIVITY_DELETED]: WS_NOTIFICATION_KEYS.CALENDARIO_ACTIVIDAD,

  [WS_EVENTS.SYSTEM_GENERAL]: WS_NOTIFICATION_KEYS.SISTEMA_GENERAL,
  [WS_EVENTS.SYSTEM_UPDATE]: WS_NOTIFICATION_KEYS.SISTEMA_ACTUALIZACION,
  [WS_EVENTS.SYSTEM_MAINTENANCE]: WS_NOTIFICATION_KEYS.SISTEMA_MANTENIMIENTO,

  [WA_INBOX_WS_EVENTS.MESSAGE_CREATED]: WS_NOTIFICATION_KEYS.WHATSAPP_INBOX_MENSAJE,

  [SOPORTE_TI_WS_EVENTS.MENSAJE_CREADO]: WS_NOTIFICATION_KEYS.SOPORTE_TI_MENSAJE,
  [SOPORTE_TI_WS_EVENTS.MENSAJE_ACTUALIZADO]: WS_NOTIFICATION_KEYS.SOPORTE_TI_MENSAJE,
  [SOPORTE_TI_WS_EVENTS.ESTADO_ACTUALIZADO]: WS_NOTIFICATION_KEYS.SOPORTE_TI_ESTADO,

  [SEGUIMIENTO_DRIVE_WS_EVENT]: WS_NOTIFICATION_KEYS.SEGUIMIENTO_DRIVE,
}
